---
name: CI

'on':
  pull_request:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      gems:
        required: false
        type: string
        default: "envkey"

jobs:
  cookstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Run Cookstyle
        run: chef exec cookstyle --display-cop-names --extra-details
        env:
          CHEF_LICENSE: accept-no-persist

  markdownlint-cli2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v10
        with:
          globs: "**/*.md"

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run YAML Linter
        uses: actionshub/yamllint@main

  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Install Gems
        run: chef gem install -N "${{ inputs.gems }}"
        if: ${{ inputs.gems }} != ""
        env:
          CHEF_LICENSE: accept-no-persist
      - name: Run RSpec
        run: chef exec rspec -f j
        env:
          CHEF_LICENSE: accept-no-persist

  integration:
    needs:
      - cookstyle
      - markdownlint-cli2
      - yamllint
      - rspec
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 'debian-10'
          - 'debian-11'
          - 'rockylinux-8'
          - 'ubuntu-2004'
          - 'ubuntu-2204'
        suite:
          - 'default'
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Run Test Kitchen
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
      - name: Print debug output on failure
        if: failure()
        run: |
            set -x
            sudo journalctl -l --since today
            KITCHEN_LOCAL_YAML=kitchen.yml /usr/bin/kitchen exec ${{ matrix.suite }}-${{ matrix.os }} -c "journalctl -l"
